# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

latex: false
language: R
cache:
  packages: true
  directories:
    - _book

script:
  # - Rscript -e "tinytex::install_tinytex()"
  - make html
  - touch _book/.nojekyll

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_PAT
  local_dir: _book
  on:
    branch: book
  target-branch: master
